[PYODBC]
ms_odbc_driver_version = 18
bfc_servers = server1@domain,server2@domain
bfi_servers = server1@domain,server2@domain
wr_servers = server1@domain,server2@domain
dw_server = server@domain

[SMTP]
smtp_recipient_list = user1@domain,user2@domain
smtp_time_out = 30

[LOGGING]
size_bytes = 50000000
logs_to_keep = 5
debug = 0

[INACTIVE THRESHOLD]
notify_bfi = 76
removal_bfi = 90
notify_bfc = 76
removal_bfc = 90
notify_wr = 76
removal_wr = 90
notify_con = 76
removal_con = 90

[EXCLUSIONS]
use_exclusions_bfi = 1
use_exclusions_bfc = 1
use_exclusions_wr = 1
use_exclusions_con = 1

[SCHEDULE]
run_time_bfi = 12:00:00
run_time_bfc = 12:02:00
run_time_wr = 12:05:00
run_time_con = 12:07:00

