[PYODBC]
ms_odbc_driver_version = 18

[SMTP]
# email addresses need to be separated by a comma without spaces. ex. user1@domain,user2@domain
smtp_recipient_list = user1@domain,user2@domain


[LOGGING]
# log rotation settings. size_bytes must be in bytes.
size_bytes = 50000000
logs_to_keep = 5
debug = False

[INACTIVE THRESHOLD]
# thresholds for inactive users
notify_bfi = 76
removal_bfi = 90
notify_bfc = 76
removal_bfc = 90
notify_wr = 76
removal_wr = 90
notify_con = 76
removal_con = 90

[EXCLUSIONS]
# use_exclusions should be set to true or false.  if use_exclusions is false, users will not be excluded from notifications and removals even if users are present in the exclusion file
use_exclusions_bfi = True
use_exclusions_bfc = True
use_exclusions_wr = True
use_exclusions_con = True

[SCHEDULE]
# configure the time the account maintenance will run. must be hh:mm:ss
run_time_bfi = 12:00:00
run_time_bfc = 12:02:00
run_time_wr = 12:05:00
run_time_con = 12:07:00

